<?php

namespace App\Support\SystemMap;

use LogicException;

class SystemMapBuilder
{
    private const WIDTH = 2680;

    private const HEIGHT = 1360;

    /** @return array{width:int,height:int,groups:list<array<string,mixed>>,nodes:list<array<string,mixed>>,edges:list<array<string,string>>,presets:array<string,list<string>>} */
    public function build(): array
    {
        $groups = [
            ['id' => 'identity', 'label' => 'Identity & representation', 'x' => 60, 'y' => 70, 'width' => 720, 'height' => 470, 'summary' => 'Who is here, how they enter, and how people and meaning are represented.'],
            ['id' => 'knowledge', 'label' => 'Contexts, knowledge & collaboration', 'x' => 820, 'y' => 70, 'width' => 900, 'height' => 560, 'summary' => 'Where collaboration lives and how human-readable knowledge, evidence and interaction are organized.'],
            ['id' => 'work', 'label' => 'Coordination & real work', 'x' => 60, 'y' => 670, 'width' => 1660, 'height' => 620, 'summary' => 'From intention and relationship through planning, agreements, commitments and observed fulfillment.'],
            ['id' => 'economy', 'label' => 'Economic truth', 'x' => 1760, 'y' => 670, 'width' => 860, 'height' => 620, 'summary' => 'Explicit economic consequences, settlement and immutable accounting truth.'],
            ['id' => 'experience', 'label' => 'Experience, reuse & operations', 'x' => 1760, 'y' => 70, 'width' => 860, 'height' => 560, 'summary' => 'How the system becomes understandable, reusable, observable and responsive to humans.'],
        ];

        $nodes = [
            $this->node('access', 'Access & invitations', 'identity', 100, 135, 'implemented',
                'Controlled entry into the platform and Groups.',
                'People can enter an appropriate collaboration without bypassing verification, admission or agreement rules.',
                'Invitation, verification and admission lifecycle evidence.',
                null,
                ['docs/PHASE_01_INVITATION_ONBOARDING.md', 'docs/ADMISSION_COLLABORATION_ARCHITECTURE.md'],
                ['app/Livewire/Platform/AccessInvitations.php', 'app/Actions/Groups/RedeemGroupInvitation.php'],
                ['Is the path obvious to a first-time invitee?', 'Are expired/revoked/reserved invitations explained safely?', 'Can no invitation path accidentally grant membership or authority?'],
                ['invitation', 'admission', 'onboarding']),
            $this->node('auth', 'Authentication', 'identity', 390, 135, 'implemented',
                'Login, verification, account status and sessions.',
                'A person can securely prove which User account is acting.',
                'Authenticated User/session state; User remains distinct from Actor.',
                route('profile.edit'),
                ['docs/PROJECT_COMPASS.md'],
                ['app/Livewire/Auth/Login.php', 'app/Models/User.php'],
                ['Does login recovery remain understandable?', 'Are inactive/unverified account boundaries consistent?', 'Are credentials kept separate from domain identity?'],
                ['login', 'user', 'security']),
            $this->node('actor', 'Actor', 'identity', 100, 300, 'implemented',
                'The domain participant behind actions and relationships.',
                'Humans and later organizations can participate without collapsing domain identity into credentials.',
                'Actor identity and acting authority.',
                route('profile.edit'),
                ['docs/PROJECT_COMPASS.md', 'docs/PHASE_04_ACTOR_PROFILE.md'],
                ['app/Models/Actor.php'],
                ['Is acting identity always explicit at mutations?', 'Can future organization/system Actors fit without weakening authority?', 'Are User and Actor responsibilities still cleanly separated?'],
                ['identity', 'person', 'authority']),
            $this->node('profile', 'Profile', 'identity', 390, 300, 'implemented',
                'Human-facing representation of an Actor.',
                'People can progressively describe themselves, their capabilities and intentions.',
                'Versioned/profile facts plus Concept assertions; not authentication truth.',
                route('profile.edit'),
                ['docs/PHASE_04_ACTOR_PROFILE.md'],
                ['app/Livewire/Profile/Manage.php'],
                ['Does the profile feel progressive rather than like one giant form?', 'Are skills, goals, interests and offers expressed through reusable semantics?', 'Can users control visibility and sharing clearly?'],
                ['profile', 'skills', 'goals']),
            $this->node('concepts', 'Concept kernel', 'identity', 100, 435, 'implemented',
                'Reusable semantic meaning and typed assertions.',
                'The same real-world meaning can be reused across skills, needs, content, Groups and discovery.',
                'Concept identity + predicates/assertions + schemes, not duplicated category trees.',
                null,
                ['docs/CONCEPT_KERNEL.md', 'docs/PHASE_03_CONCEPT_KERNEL.md'],
                ['app/Models/Concept.php', 'app/Models/ConceptAssertion.php'],
                ['Are we duplicating concepts that should be predicates?', 'Can users understand the semantics through purpose-specific UI?', 'Are provenance and visibility strong enough for cross-module reuse?'],
                ['semantics', 'taxonomy', 'assertion']),

            $this->node('groups', 'Groups & governance', 'knowledge', 860, 135, 'implemented',
                'Governed community/team boundary with membership and contextual permissions.',
                'People can organize together with explicit ownership, roles, agreements and participation rules.',
                'Membership and contextual authorization history.',
                route('groups.index'),
                ['docs/CURRENT_STATE.md', 'docs/CAPABILITY_MESH_ARCHITECTURE.md'],
                ['app/Models/Group.php', 'app/Policies/GroupPolicy.php'],
                ['Are ownership and role changes race-safe and understandable?', 'Are platform, Group and Context authority visibly distinct?', 'Can a Group grow without navigation becoming governance-heavy?'],
                ['group', 'membership', 'permissions']),
            $this->node('agreements', 'Group agreements', 'knowledge', 1140, 135, 'implemented',
                'Versioned Group-wide terms with explicit acceptance.',
                'Participants know which rules they accepted and historical terms never silently change.',
                'Exact immutable Agreement version + acceptance evidence.',
                null,
                ['docs/PROJECT_COMPASS.md', 'docs/CURRENT_STATE.md'],
                ['app/Models/GroupAgreement.php'],
                ['Is the distinction from negotiated Contracts obvious?', 'Are effective dates and reacceptance understandable?', 'Should authored terms reference sealed Content more directly?'],
                ['agreement', 'terms', 'acceptance']),
            $this->node('contexts', 'Context', 'knowledge', 1420, 135, 'implemented',
                'Reusable collaboration and visibility boundary.',
                'Work can happen in Personal, Admission, Relationship, Contract or Group-space settings without reinventing access rules.',
                'Context identity plus explicit authorization contract.',
                route('contexts.personal'),
                ['docs/PROJECT_COMPASS.md', 'docs/PHASE_05_GENERIC_CONTENT_CONTEXT.md'],
                ['app/Models/Context.php'],
                ['Are all new collaboration surfaces using Context instead of bespoke silos?', 'Is access explainable independently from Group membership?', 'Are Context capabilities composable enough?'],
                ['context', 'scope', 'authorization']),
            $this->node('content', 'Content & revisions', 'knowledge', 860, 315, 'implemented',
                'Universal human-facing artifact layer with structure, revisions and publication.',
                'People can author readable, interactive, versioned knowledge without domain truth becoming mutable prose.',
                'Sealed Content revisions and publication evidence.',
                route('content.library'),
                ['docs/PHASE_05_GENERIC_CONTENT_CONTEXT.md', 'docs/PHASE_06_CONTENT_BLUEPRINTS.md'],
                ['app/Models/SpaceContent.php', 'app/Models/ContentRevision.php'],
                ['Is authoring friction low enough for normal users?', 'Are published and draft states always obvious?', 'Are domain actions linked from Content without turning prose into authority?'],
                ['content', 'revision', 'publication']),
            $this->node('conversation', 'Conversation', 'knowledge', 1140, 315, 'implemented',
                'Context-scoped human collaboration stream.',
                'People can discuss, clarify and attach evidence around work while authoritative decisions stay explicit.',
                'Durable messages and assets; conversation wording is not approval/acceptance truth.',
                null,
                ['docs/PHASE_11_CONVERSATION_TIMELINE.md', 'docs/PROJECT_COMPASS.md'],
                ['app/Livewire/Contexts/Conversation.php'],
                ['Are authoritative actions visually distinguishable from discussion?', 'Can conversation scale without losing task/evidence context?', 'Are audience/privacy rules always clear?'],
                ['conversation', 'message', 'collaboration']),
            $this->node('submissions', 'Submissions & review', 'knowledge', 1420, 315, 'implemented',
                'Structured response, evidence and evaluation flow.',
                'Applications, exams, inspections and other responses can be reviewed against explicit structure.',
                'Submission/response/review records and evidence.',
                null,
                ['docs/PHASE_07_SUBMISSION_EVALUATION.md'],
                ['app/Livewire/Interactions/ReviewQueue.php', 'app/Models/Submission.php'],
                ['Can a submitter understand what is required before submitting?', 'Can reviewers trace every answer/evidence item?', 'Are evaluation rules reusable without hiding domain meaning?'],
                ['submission', 'review', 'evaluation']),
            $this->node('timeline', 'Unified timeline', 'knowledge', 1000, 480, 'implemented',
                'Read-only projection of source-linked events in a Context.',
                'Humans can understand what happened across modules without duplicating source truth.',
                'Source-domain events projected with authorization; source objects remain authoritative.',
                null,
                ['docs/PHASE_11_CONVERSATION_TIMELINE.md'],
                ['app/Livewire/Contexts/Timeline.php'],
                ['Does every timeline item link back to the authoritative source?', 'Is chronological density manageable?', 'Can filters reveal a coherent story without hiding important events?'],
                ['timeline', 'events', 'history']),
            $this->node('evidence', 'Evidence & interactions', 'knowledge', 1340, 480, 'implemented',
                'Assets, annotations, references and interaction around exact content/work.',
                'Humans can point to what actually supports a statement, submission or fulfillment.',
                'Immutable/referenceable evidence plus permission-aware interaction metadata.',
                null,
                ['docs/CURRENT_STATE.md'],
                ['app/Models/ContentEvidenceReference.php', 'app/Models/Asset.php'],
                ['Can users create evidence from every place that asks for it?', 'Is provenance obvious after reuse?', 'Are annotations separated from authoritative domain facts?'],
                ['evidence', 'asset', 'annotation']),

            $this->node('intents', 'Needs, offers & matching', 'work', 100, 735, 'implemented',
                'Structured expression of what someone needs or can offer.',
                'People can discover opportunities without a marketplace being required for direct human coordination.',
                'Intent facts and deterministic match explanations; matching creates no agreement.',
                route('intents.index'),
                ['docs/PHASE_19_NEED_OFFER_MATCHING.md'],
                ['app/Livewire/Intents/Directory.php'],
                ['Are filters and match explanations useful to humans?', 'Is direct Proposal/Contract creation still possible without matching?', 'Do intent semantics reuse Concepts rather than duplicate them?'],
                ['need', 'offer', 'matching']),
            $this->node('relationships', 'Relationships', 'work', 390, 735, 'implemented',
                'Explicit collaboration between Actors with purpose and shared Context.',
                'People who already know each other can coordinate directly.',
                'Relationship participants, state and provenance.',
                route('relationships.index'),
                ['docs/PHASE_10_RELATIONSHIP_CONTEXT.md'],
                ['app/Models/Relationship.php', 'app/Livewire/Relationships/Show.php'],
                ['Does a relationship surface the next meaningful actions?', 'Is its Context useful without overwhelming users?', 'Are participant roles and authority easy to understand?'],
                ['relationship', 'collaboration', 'context']),
            $this->node('proposals', 'Proposal & negotiation', 'work', 680, 735, 'implemented',
                'Explicit proposed terms before binding agreement.',
                'Humans can negotiate changes without silently rewriting history.',
                'Proposal versions, responses and provenance.',
                route('proposals.index'),
                ['docs/PHASE_14_PROPOSAL_NEGOTIATION.md'],
                ['app/Models/Proposal.php', 'app/Livewire/Proposals/Show.php'],
                ['Can people compare versions and understand what changed?', 'Is acceptance clearly distinct from discussion?', 'Can proposals begin from direct relationships and matched intents equally?'],
                ['proposal', 'negotiation', 'terms']),
            $this->node('contracts', 'Contracts', 'work', 970, 735, 'implemented',
                'Versioned accepted terms between explicit parties.',
                'People know exactly which terms govern work and future changes cannot rewrite past agreements.',
                'Accepted immutable ContractVersion plus party acceptances.',
                route('contracts.index'),
                ['docs/PHASE_15_CONTRACT_VERSION_ACCEPTANCE.md'],
                ['app/Models/Contract.php', 'app/Models/ContractVersion.php'],
                ['Is the active governing version unmistakable?', 'Are amendments/effective dates understandable?', 'Do downstream commitments always preserve exact contract provenance?'],
                ['contract', 'acceptance', 'version']),
            $this->node('commitments', 'Commitments', 'work', 1260, 735, 'implemented',
                'Concrete obligations created from accepted terms.',
                'Broad agreements become explicit things someone must perform, deliver, pay or attend.',
                'Commitment lifecycle and source ContractVersion.',
                null,
                ['docs/PHASE_16_COMMITMENT_FULFILLMENT.md'],
                ['app/Models/Commitment.php'],
                ['Can users see who owes what to whom and by when?', 'Does every commitment preserve exact source terms?', 'Are schedule/payment commitments composed instead of duplicated?'],
                ['commitment', 'obligation', 'work']),
            $this->node('service_economics', 'Paid service workflow', 'work', 680, 1120, 'implemented',
                'Structured unit-priced service terms that connect an accepted ContractVersion to generated work, earned value and periodic cash settlement.',
                'Employer and worker can agree one exact unit/rate/schedule, execute shared work, and always see earned, awaiting-confirmation, settled and outstanding value.',
                'Immutable ContractServiceTerm + generated Commitment/Plan + accepted Fulfillment + deterministic FinancialObligation; Settlement remains separately confirmed.',
                null,
                ['docs/PHASE_23_IDEAL_SERVICE_FINANCIAL_WORKFLOW.md', 'docs/FINANCIAL_ARCHITECTURE.md'],
                ['app/Models/ContractServiceTerm.php', 'app/Actions/Contracts/BootstrapContractServiceWorkflow.php', 'app/Actions/Financial/ProposeContractSettlementBatch.php'],
                ['Can a new employer/worker complete the full cash workflow without understanding kernel names?', 'Are unit, rate, due cycle and schedule unmistakable before Contract acceptance?', 'Can every total be traced back to exact work and exact ContractVersion?', 'Is awaiting payment clearly different from confirmed settlement and Accounting posting?'],
                ['employment', 'service', 'rate', 'cash', 'settlement']),
            $this->node('planner', 'Planner & temporal fabric', 'work', 100, 955, 'implemented',
                'Plans, recurring rules, concrete occurrences, reminders and actual execution.',
                'People can plan intended work and record what really happened in their own calendar/timezone.',
                'Plan schedule intent + immutable occurrence schedule + actual execution timestamps.',
                route('planner.index'),
                ['docs/PHASE_12_PERSONAL_ACTIVITY_PLANNER.md'],
                ['app/Models/Plan.php', 'app/Models/PlanOccurrence.php'],
                ['Are scheduled intent and actual execution visually distinct?', 'Can dense calendars stay navigable as many temporal providers arrive?', 'Do prerequisites, evidence and costs help prepare/learn without pretending to be authority?'],
                ['planner', 'calendar', 'time']),
            $this->node('fulfillment', 'Fulfillment', 'work', 520, 955, 'implemented',
                'Evidence-bearing record of what happened against a Commitment.',
                'A person can prove performance and a counterparty can accept, reject or dispute it explicitly.',
                'Fulfillment state, evidence and authorized review.',
                null,
                ['docs/PHASE_16_COMMITMENT_FULFILLMENT.md'],
                ['app/Models/Fulfillment.php'],
                ['Can evidence be attached naturally from the Planner/work surface?', 'Is accepted versus disputed performance obvious?', 'Can no financial consequence be inferred before the required acceptance step?'],
                ['fulfillment', 'evidence', 'review']),
            $this->node('journeys', 'Journeys & domain blueprints', 'work', 940, 955, 'implemented',
                'Reusable guided compositions over generic kernels.',
                'A normal user experiences a focused workflow instead of generic infrastructure.',
                'Versioned blueprint configuration over trusted capabilities.',
                route('journeys.index'),
                ['docs/PHASE_18_DOMAIN_BLUEPRINTS.md'],
                ['app/Livewire/Journeys/Index.php'],
                ['Do generic kernels disappear behind purpose-specific UX?', 'Can two genuinely different domains prove each reusable abstraction?', 'Are blueprint versions and capability boundaries inspectable?'],
                ['journey', 'blueprint', 'domain']),
            $this->node('home', 'Home / Today', 'work', 1260, 955, 'implemented',
                'Personal operational surface composed from authoritative sources.',
                'A person can answer “what needs my attention now?” without visiting every module.',
                'Read-only/action-linked projections from Planner, reviews, notifications and other source domains.',
                route('dashboard'),
                ['docs/PHASE_21_HOME_TODAY.md'],
                ['app/Livewire/Home/Today.php'],
                ['Does Today prioritize action rather than become another dashboard dump?', 'Can every card explain its source and next action?', 'Does it remain fast as more providers contribute?'],
                ['today', 'dashboard', 'attention']),

            $this->node('obligations', 'Financial obligations', 'economy', 1800, 735, 'implemented',
                'Explicit economic consequence recognized from accepted performance.',
                'People can distinguish what was agreed, what was done, what is owed and what has been paid.',
                'Immutable FinancialObligation bound to accepted Fulfillment and exact ContractVersion.',
                null,
                ['docs/PHASE_17_FINANCIAL_OBLIGATION_SETTLEMENT.md', 'docs/FINANCIAL_ARCHITECTURE.md'],
                ['app/Models/FinancialObligation.php'],
                ['Is recognition intuitive after accepted fulfillment?', 'Can users explain earned/paid/outstanding/disputed without accounting jargon?', 'Are bilateral privacy and idempotency visible and tested?'],
                ['financial', 'obligation', 'earned']),
            $this->node('settlements', 'Settlement', 'economy', 2090, 735, 'implemented',
                'Counterparty-confirmed payment claim against an obligation.',
                'A payment record becomes shared truth only through explicit confirmation.',
                'Settlement lifecycle; external-bank truth is not implied.',
                null,
                ['docs/PHASE_17_FINANCIAL_OBLIGATION_SETTLEMENT.md'],
                ['app/Models/Settlement.php'],
                ['Is proposed versus confirmed payment unmistakable?', 'Can partial payments/refusals be understood?', 'Is external verification clearly separated from internal confirmation?'],
                ['settlement', 'payment', 'confirmation']),
            $this->node('accounting', 'Personal accounting', 'economy', 2380, 735, 'implemented',
                'Balanced immutable ledger for personal financial truth.',
                'People can understand balances, income, expenses and transfers without needing to think in debit/credit terminology.',
                'Balanced JournalEntry/JournalLine records in the Actor\'s Personal Ledger.',
                route('accounting.index'),
                ['docs/PHASE_13_PERSONAL_ACCOUNTING.md', 'docs/FINANCIAL_ARCHITECTURE.md'],
                ['app/Models/Ledger.php', 'app/Models/JournalEntry.php', 'app/Livewire/Accounting/Index.php'],
                ['Are routine money actions simple enough for daily use?', 'Can every balance change be explained and reversed/corrected safely?', 'Is the bridge from obligation/settlement explicit instead of silently posting?', 'What is missing for reconciliation, budgeting and financial review?'],
                ['accounting', 'ledger', 'expense', 'income']),
            $this->node('financial_lab', 'Financial laboratory', 'economy', 1800, 970, 'direction',
                'Separate sandbox for experiments about value, credits and instruments.',
                'Groups can explore value ideas without corrupting real accounting or silently creating redeemable money.',
                'Future experimental instrument/valuation truth, explicitly separated from production Accounting.',
                null,
                ['docs/FINANCIAL_ARCHITECTURE.md'],
                [],
                ['What experiments are genuinely useful before building infrastructure?', 'How will laboratory value remain isolated from production ledger truth?', 'Which ideas require legal/payment-provider review before any real-money path exists?'],
                ['future', 'finance', 'instrument', 'simulation']),
            $this->node('payments', 'External payments & reconciliation', 'economy', 2090, 970, 'direction',
                'Controlled future bridge to external money movement.',
                'People can eventually connect provider-confirmed money movement without confusing provider status with ledger truth.',
                'Future provider attempts, confirmations and reconciliation evidence.',
                null,
                ['docs/FINANCIAL_ARCHITECTURE.md'],
                [],
                ['Which provider/use case justifies this complexity?', 'How will webhook idempotency and reconciliation be proven?', 'What compliance/operational controls are required before enabling real money?'],
                ['future', 'payments', 'reconciliation']),
            $this->node('finance_review', 'Finance review lens', 'economy', 2380, 970, 'implemented',
                'Map lens tying Planner costs, performance, obligations, settlement and Accounting together.',
                'A reviewer can inspect financial UX as one human story while preserving separate sources of truth.',
                'No new financial authority: this is an explanatory composition.',
                route('system-map', ['lens' => 'finance']),
                ['docs/FINANCIAL_ARCHITECTURE.md'],
                ['app/Support/SystemMap/SystemMapBuilder.php'],
                ['Can the human trace “planned cost → actual work → owed → paid → accounted”?', 'Where are duplicate data entry or unclear handoffs?', 'Which financial module should be refined next?'],
                ['finance', 'review', 'map']),

            $this->node('notifications', 'Notifications & realtime', 'experience', 1800, 135, 'implemented',
                'Durable notification inbox plus realtime transport.',
                'People receive timely signals without realtime delivery becoming authoritative state.',
                'Database notification/read truth; broadcasts are transport only.',
                route('notifications.index'),
                ['docs/PHASE_22_REALTIME_NOTIFICATIONS.md'],
                ['app/Livewire/Notifications/Index.php'],
                ['Are notifications actionable and deduplicated?', 'Can users recover after missed realtime delivery?', 'Will alert volume remain humane as modules grow?'],
                ['notification', 'realtime', 'outbox']),
            $this->node('manual', 'System manual', 'experience', 2090, 135, 'implemented',
                'Versioned human documentation built with the Content system.',
                'People can understand not just concepts, but exactly how to use each part of the product.',
                'Official sealed documentation Content plus distinct learning overlays.',
                route('manual'),
                ['docs/IET_DEVELOPER_SYSTEM_HANDBOOK.md', 'docs/PROJECT_COMPASS.md'],
                ['app/Http/Controllers/SystemManualController.php'],
                ['Does every important UI block explain how to use it?', 'Can a user report an issue from the exact related concept?', 'Are docs synchronized with each release without overwriting community/personal learning?'],
                ['docs', 'manual', 'learning']),
            $this->node('system_map', 'System map', 'experience', 2380, 135, 'implemented',
                'Interactive architecture/meaning map of the platform.',
                'Humans and maintainers can see the whole organism, focus one concept and understand how it serves real needs.',
                'Curated explanatory projection of current repository architecture; never domain authority.',
                route('system-map'),
                ['docs/SYSTEM_MAP_VISION.md', 'docs/PROJECT_COMPASS.md'],
                ['app/Support/SystemMap/SystemMapBuilder.php', 'resources/js/system-map.js'],
                ['Does the map reveal missing links rather than become decoration?', 'Can every major module explain its human purpose and authoritative truth?', 'Can future versions derive more of the map safely from code/docs metadata?'],
                ['architecture', 'map', 'review']),
            $this->node('blueprints', 'Reusable blueprints', 'experience', 1800, 325, 'implemented',
                'Versioned reusable structures that turn generic kernels into focused experiences.',
                'Successful workflows can be reused without cloning new identity/content/planner/accounting stacks.',
                'Trusted versioned configuration, not arbitrary executable code.',
                route('journeys.index'),
                ['docs/PHASE_06_CONTENT_BLUEPRINTS.md', 'docs/PHASE_18_DOMAIN_BLUEPRINTS.md'],
                ['app/Models/ContentBlueprint.php', 'app/Models/DomainBlueprint.php'],
                ['Are successful structures easy to discover/reuse?', 'Are configuration boundaries safe?', 'Does reuse preserve provenance and version clarity?'],
                ['blueprint', 'reuse', 'configuration']),
            $this->node('operations', 'Operations & release safety', 'experience', 2090, 325, 'implemented',
                'CI, migrations, backup/restore, queues, scheduler, security and release gates.',
                'The system can be trusted not only in a demo but through change, failure and recovery.',
                'Operational evidence and immutable release checkpoints.',
                null,
                ['docs/OPERATIONS_RUNBOOK.md', 'docs/PUBLISHABLE_V1_RELEASE_GATE.md', 'docs/SECURITY_UPDATE_PROCESS.md'],
                ['.github/workflows/ci.yml'],
                ['Are backups actually restorable?', 'Are queues/scheduler/realtime supervised in production?', 'Can a release be traced to exact code, docs and acceptance evidence?'],
                ['operations', 'ci', 'release']),
            $this->node('ai', 'AI assistance', 'experience', 2380, 325, 'direction',
                'Future contextual assistant that can explain and help structure user intent.',
                'People can describe what they want in natural language while retaining explicit review and control over authoritative changes.',
                'Future assistance layer; domain Actions and authorization remain authoritative.',
                null,
                ['docs/PROJECT_COMPASS.md'],
                [],
                ['Which tasks benefit from assistance without hiding structure?', 'How will every proposed mutation remain reviewable?', 'How will context-specific help map to exact docs and domain actions?'],
                ['future', 'ai', 'assistant']),
        ];

        $edges = [
            $this->edge('access', 'auth', 'enters through'),
            $this->edge('auth', 'actor', 'acts as'),
            $this->edge('actor', 'profile', 'is represented by'),
            $this->edge('profile', 'concepts', 'describes meaning with'),
            $this->edge('actor', 'groups', 'participates in'),
            $this->edge('groups', 'agreements', 'governs with'),
            $this->edge('groups', 'contexts', 'hosts collaboration in'),
            $this->edge('agreements', 'contexts', 'constrains participation in'),
            $this->edge('contexts', 'content', 'contains'),
            $this->edge('contexts', 'conversation', 'contains'),
            $this->edge('contexts', 'submissions', 'scopes'),
            $this->edge('contexts', 'timeline', 'projects events into'),
            $this->edge('content', 'evidence', 'can anchor'),
            $this->edge('content', 'submissions', 'can request'),
            $this->edge('conversation', 'evidence', 'can attach'),
            $this->edge('submissions', 'evidence', 'collects'),
            $this->edge('concepts', 'intents', 'gives meaning to'),
            $this->edge('intents', 'relationships', 'may hand off to'),
            $this->edge('actor', 'relationships', 'forms'),
            $this->edge('relationships', 'contexts', 'owns shared'),
            $this->edge('relationships', 'proposals', 'can negotiate through'),
            $this->edge('proposals', 'contracts', 'may become'),
            $this->edge('contracts', 'commitments', 'may create generic'),
            $this->edge('contracts', 'service_economics', 'fixes unit-priced terms for'),
            $this->edge('service_economics', 'commitments', 'auto-generates'),
            $this->edge('service_economics', 'planner', 'auto-generates schedule in'),
            $this->edge('service_economics', 'obligations', 'prices accepted work into'),
            $this->edge('service_economics', 'settlements', 'groups cash payment through'),
            $this->edge('commitments', 'planner', 'may schedule'),
            $this->edge('commitments', 'fulfillment', 'is performed through'),
            $this->edge('planner', 'fulfillment', 'provides execution evidence to'),
            $this->edge('planner', 'timeline', 'projects schedule/execution to'),
            $this->edge('fulfillment', 'evidence', 'uses'),
            $this->edge('fulfillment', 'obligations', 'accepted work may create'),
            $this->edge('obligations', 'settlements', 'is paid through'),
            $this->edge('obligations', 'accounting', 'may explicitly post to'),
            $this->edge('settlements', 'accounting', 'may explicitly post to'),
            $this->edge('accounting', 'timeline', 'projects entries to'),
            $this->edge('planner', 'home', 'feeds'),
            $this->edge('submissions', 'home', 'feeds attention into'),
            $this->edge('notifications', 'home', 'feeds attention into'),
            $this->edge('planner', 'notifications', 'emits reminders to'),
            $this->edge('proposals', 'notifications', 'emits lifecycle signals to'),
            $this->edge('obligations', 'notifications', 'emits financial signals to'),
            $this->edge('blueprints', 'content', 'configures'),
            $this->edge('blueprints', 'journeys', 'composes'),
            $this->edge('journeys', 'planner', 'guides'),
            $this->edge('manual', 'content', 'is authored with'),
            $this->edge('system_map', 'manual', 'links architecture understanding to'),
            $this->edge('operations', 'notifications', 'supports delivery of'),
            $this->edge('financial_lab', 'accounting', 'must remain separate from', 'boundary'),
            $this->edge('payments', 'settlements', 'may externally verify', 'direction'),
            $this->edge('payments', 'accounting', 'reconciles with', 'direction'),
            $this->edge('finance_review', 'planner', 'reviews planned/actual cost around'),
            $this->edge('finance_review', 'obligations', 'reviews'),
            $this->edge('finance_review', 'settlements', 'reviews'),
            $this->edge('finance_review', 'accounting', 'reviews'),
            $this->edge('ai', 'system_map', 'can later use as contextual topology', 'direction'),
            $this->edge('ai', 'manual', 'can later ground explanations in', 'direction'),
        ];

        $this->validate($nodes, $edges);

        return [
            'width' => self::WIDTH,
            'height' => self::HEIGHT,
            'groups' => $groups,
            'nodes' => $nodes,
            'edges' => $edges,
            'presets' => [
                'north_star' => ['auth', 'actor', 'contexts', 'content', 'planner', 'intents', 'relationships', 'proposals', 'contracts', 'service_economics', 'commitments', 'fulfillment', 'obligations', 'settlements', 'accounting', 'blueprints'],
                'finance' => ['contracts', 'service_economics', 'commitments', 'planner', 'fulfillment', 'obligations', 'settlements', 'accounting', 'financial_lab', 'payments', 'finance_review'],
                'content' => ['contexts', 'content', 'conversation', 'submissions', 'timeline', 'evidence', 'manual', 'blueprints'],
                'community' => ['actor', 'groups', 'agreements', 'contexts', 'conversation', 'relationships'],
                'execution' => ['contracts', 'service_economics', 'commitments', 'planner', 'fulfillment', 'evidence', 'home', 'notifications'],
            ],
        ];
    }

    /**
     * @param  list<string>  $docs
     * @param  list<string>  $code
     * @param  list<string>  $review
     * @param  list<string>  $tags
     * @return array<string,mixed>
     */
    private function node(
        string $id,
        string $label,
        string $group,
        int $x,
        int $y,
        string $status,
        string $summary,
        string $humanPurpose,
        string $truth,
        ?string $route,
        array $docs,
        array $code,
        array $review,
        array $tags,
    ): array {
        return compact(
            'id',
            'label',
            'group',
            'x',
            'y',
            'status',
            'summary',
            'humanPurpose',
            'truth',
            'route',
            'docs',
            'code',
            'review',
            'tags',
        );
    }

    /** @return array<string,string> */
    private function edge(string $source, string $target, string $label, string $kind = 'flow'): array
    {
        return compact('source', 'target', 'label', 'kind');
    }

    /**
     * @param  list<array<string,mixed>>  $nodes
     * @param  list<array<string,string>>  $edges
     */
    private function validate(array $nodes, array $edges): void
    {
        $ids = array_column($nodes, 'id');

        if (count($ids) !== count(array_unique($ids))) {
            throw new LogicException('System Map node IDs must be unique.');
        }

        $known = array_fill_keys($ids, true);

        foreach ($edges as $edge) {
            if (! isset($known[$edge['source']], $known[$edge['target']])) {
                throw new LogicException("System Map edge [{$edge['source']} -> {$edge['target']}] references an unknown node.");
            }
        }
    }
}
